w8--backend/notes/search-app/config/routes.rb
Rails.application.routes.draw do

  resources :search, only: [:index]
  resources :artists, only: [:index, :show]
end

w8--backend/notes/search-app/app/models/artist.rb
class Artist < ApplicationRecord
  include PgSearch

  pg_search_scope :search_name, against: [:name]
  pg_search_scope :search_all_variants,
    against: [:name, :bio],
    using: {
      tsearch: { dictionary: 'english' } # This searches all word variants
    }
  pg_search_scope :search_all_partial_matches,
    against: [:name, :bio],
    using: {
      tsearch: { prefix: true } #This enables partial word searching
    }
end

w8--backend/notes/search-app/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.params(:id)
  end
end

w8--backend/notes/search-app/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if search_params[:search_term].present?
     @results = Artist.search_all(search_params[:search_term])
   else
     @results = Artist.all
   end
  end

  private
    def search_params
      params.permit(:search_term)
    end
end

w8--backend/notes/search-app/app/helpers/artists_helper.rb
module ArtistsHelper
end

w8--backend/notes/search-app/app/helpers/search_helper.rb
module SearchHelper
end

w8--backend/notes/search-app/app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

w8--backend/notes/search-app/app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

w8--backend/notes/search-app/app/views/search/index.html.erb
<h1>Search</h1>

<%= form_tag search_index_path, method: :get do %>
  <p>
    <%= text_field_tag :search_term, params[:search_term] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

<section class="results">
  <% @results.each do |artist| %>
    <h3><%= artist.name %></h3>
    <div class="bio">
      <p><%= artist.bio %></p>
    </div>
  <% end %>
</section>